---
- name: Configurar perfil por defecto (para ofimática)
  hosts: perfil_por_defecto
  tasks:
    - name: Instalar paquetes de ofimática
      apt:
        name:
          - libreoffice
          - gimp
        state: present

    - name: Crear grupo "office" si no existe
      group:
        name: office
        state: present
    - name: Agregar usuario al grupo "office"
      user:
        name: usuario_oficinista
        groups: office
        append: yes
    - name: Crear directorio de documentos compartidos
      file:
        path: /home/usuario_oficinista/documentos_compartidos
        state: directory
        owner: usuario_oficinista
        group: office
        mode: '0775'


- name: Configurar perfil alternativo (para desarrolladores)
  hosts: perfil_alternativo
  tasks:
    - name: Instalar paquetes para desarrollo
      apt:
        name:
          - git
          - python3
          - build-essential
          - code
        state: present

    - name: Crear grupo "developers" si no existe
      group:
        name: developers
        state: present

    - name: Agregar usuario al grupo "developers"
      user:
        name: usuario_desarrollador
        groups: developers
        append: yes
    - name: Clonar repositorio de código fuente
      git:
        repo: https://github.com/UCLM-ESI/upper
        dest: /home/usuario_desarrollador/proyecto
        clone: yes
        update: no
        force: yes
        owner: usuario_desarrollador
        group: developers
---