---
- name: Configurar perfil por defecto (para ofimática)
  hosts: perfil_por_defecto
  become: yes
  vars:
    ansible_become_pass: "usuario-1"
  tasks:
    - name: Crear grupo "office" si no existe
      group:
        name: office
        state: present

    - name: Crear nuevo usuario
      user:
        name: usuario_oficinista
        groups: office
        append: yes
        shell: /bin/bash
        create_home: yes
        password: "{{ 'oficina1' | password_hash('sha512') }}"

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes de ofimática
      apt:
        name:
          - libreoffice
          - gimp
        state: present

    - name: Crear directorio de documentos compartidos
      file:
        path: /home/usuario_oficinista/documentos_compartidos
        state: directory
        owner: usuario_oficinista
        group: office
        mode: "0775"
    
    - name: notificar por Telegram
      telegram:
        token: "###"
        chat_id: "###"
        msg: "Aprovisionamiento oficinista finalizado. IP del nodo aprovisionado: {{ ansible_host }}"
      when: ansible_host is defined and ansible_host != ""

#######################################################################################################

- name: Configurar perfil alternativo (para desarrolladores)
  hosts: perfil_alternativo
  become: yes
  vars:
    ansible_become_pass: "usuario-1"
  tasks:
    - name: Crear grupo "developers" si no existe
      group:
        name: developers
        state: present

    - name: Agregar usuario al grupo "developers"
      user:
        name: usuario_desarrollador
        groups: developers
        append: yes
        shell: /bin/bash
        create_home: yes
        password: "{{ 'desarrollo1' | password_hash('sha512') }}"

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes para desarrollo
      become: yes
      apt:
        name:
          - git
          - python3
          - build-essential
          - neovim
        state: present

    - name: Clonar repositorio de código fuente
      git:
        repo: https://github.com/UCLM-ESI/upper
        dest: /home/usuario_desarrollador/proyecto
        clone: yes
        update: no
        force: yes

    - name: Establecer propietario y grupo del directorio clonado
      file:
        path: /home/usuario_desarrollador/proyecto
        owner: usuario_desarrollador
        group: developers
        state: directory
        recurse: yes
    
    - name: notificar por Telegram
      telegram:
        token: "###"
        chat_id: "###"
        msg: "Aprovisionamiento oficinista finalizado. IP del nodo aprovisionado: {{ ansible_host }}"
      when: ansible_host is defined and ansible_host != ""
